### ISSUE TITLE
Gambio 4.6.0.2 issue

### ISSUE THREAD

**Issue by bagorob** [mollie/gambio#68] opened 2022-11-18 10:31 UTC
Hi,

got this in the logfile:

WARNING: constant(): Couldn't find constant MODULE_PAYMENT_MOLLIE_KLARNAPAYNOW_STATUS
WARNING: constant(): Couldn't find constant MODULE_PAYMENT_MOLLIE_KLARNAPAYNOW_SORT_ORDER
and so on..

using 3.0.14

**Comment by tanjalog** [comment] 2022-11-25 14:46
Hey @bagorob,

Thank you for your patience.

Please note that our development team has reproduced this issue locally and fixed it.

The problem was:

These constants SORT_ORDER, STATUS, and ISSUER_LIST are defined when the payment method is installed. But the plugin accessed them for payment methods that weren't installed.

Also, we have found the warning log about accessing the constants for surcharge calculation that should contain the payment method in name, when the payment method is null. This happens at the checkout while payment method is not chosen. This problem is fixed too.

We will include this change in the release that will be next week.

We will update you regarding this.

Best regards.

**Comment by tanjalog** [comment] 2022-12-01 09:47
Hello @bagorob,

Please note regarding your issue that our team needed to verify additional steps before releasing a new version.

During that process, we concluded that plugins for other versions, also have the same issues.

Now our team is fixing these plugins and testing them.

We apologize for these unforeseen circumstances and be sure that a new release will be available next week.

We will update you timely regarding this.

Thank you very much for understanding.

Best regards.

**Comment by tanjalog** [comment] 2022-12-08 09:44
Hey @bagorob, 

Thank you for your patience.

Please note that we experienced unexpected issues regarding permissions for releasing a new version so we are not able to do the release this week.

We have to apologize for this unpredicted postponement and be assured that release will be available at the beginning of the next week.

We will keep you posted.

Thanks for understanding,

Best regards

**Comment by tanjalog** [comment] 2022-12-12 15:36
Hey @bagorob,

Thank you for your patience and understanding during resolving of this request.

Please note that all new plugin versions for:

Gambio 3.0.x - 3.4.x (v0.1.13),

Gambio 3.5.x - 4.0.x (v1.0.12),

Gambio 4.1.x - 4.4.x (v2.0.13),

Gambio 4.5.x - 4.x.x (v3.0.15)

are released.

As we inform you, the release also contains changes from https://github.com/mollie/gambio/issues/69

Best regards.

**Closed as completed** 2022-12-14 10:29 UTC
