### ISSUE TITLE
Incompatible with Gambio Version: v4.4.0.4

### ISSUE THREAD

**Issue by adrijanb** [mollie/gambio#56] opened 2022-02-23 00:25 UTC
Hi, 

After installing the newest mollie module for my customer, the whole store crashed. It only shows the HTTP ERROR 500. 
We cannot debug this further, the webhost does not allow to access the error log :/

Could you check?

**Comment by logeecom** [comment] 2022-03-02 08:31
Thank you for reaching out! We are investigating this issue and will get back to you with more information.

**Comment by logeecom** [comment] 2022-03-04 15:54
Please note that we did not manage to reproduce the reported issue. After installing the latest module version 2.0.11 on Gambio 4.4.0.4 the module works as expected and there are no fatal errors.

Can you please give us more information about this environment so that we can manage to reproduce the behavior and continue with the investigation?

**Comment by logeecom** [comment] 2022-04-15 07:48
Please note that we are closing this issue from our side since it has been more than a month without any response from your side. Please feel free to reopen this ticket if you continue experiencing this issue and please provide us with more information.

**Closed as completed** 2022-04-15 07:50 UTC
